name: Marcus Tan's Website
title: Marcus Tan's Website
description: Blah blah blah
email: marcus@mtss.dev
url: https://github.com/marcustan-dev/mysite
baseurl: ''
logo: https://avatars1.githubusercontent.com/u/54130573
cover: https://avatars1.githubusercontent.com/u/54130573
resume: https://avatars1.githubusercontent.com/u/54130573
social:
  - title: email
    url: mailto:marcus@mtss.dev
  - title: github
    url: https://github.com/marcustan-dev
  - title: linkedin
    url: https://www.linkedin.com/in/marcustanzw

markdown: kramdown
permalink: /notes/:year/:month/:day/:title

plugins_dir:
  # - jekyll-feed
  - jekyll-seo-tag
  - jekyll-coffeescript
  - jekyll-minifier
  - jekyll-sitemap

# Google-analytics
google-analytics:
  id: ""

keep_files:
  - CNAME

exclude: 
  - package.json
  - node_modules
  - GEMFILE
  - Gemfile.lock
  - package-lock.json
